export const allProducts = [
  // === Bras ===
  {
    id: "bra1",
    name: "Padded Push-Up Bra",
    collection: "bras",
    category: "push-up",
    price: "Rs. 1,500",
    description: "Soft padded push-up bra with underwire for enhanced lift and shape.",
    image: "/padded.jpg",
  },
  {
    id: "bra2",
    name: "Sports Bra",
    collection: "bras",
    category: "sports",
    price: "Rs. 1,200",
    description: "High-impact sports bra perfect for gym and workouts.",
    image: "/sportsbra.jpg",
  },
  {
    id: "bra3",
    name: "Basic T-Shirt Bra",
    collection: "bras",
    category: "t-shirt",
    price: "Rs. 1,350",
    description: "Lightly padded everyday t-shirt bra for comfort and seamless finish.",
    image: "/tshirtbra.jpg",
  },
  {
    id: "bra4",
    name: "Lace Bra",
    collection: "bras",
    category: "lace",
    price: "Rs. 1,600",
    description: "Romantic lace bra with fine detailing and soft cups.",
    image: "/lacebra.jpg",
  },
  {
    id: "bra5",
    name: "Wire-Free Comfort Bra",
    collection: "bras",
    category: "full-coverage",
    price: "Rs. 1,300",
    description: "All-day support without the wire.",
    image: "/wirefree.jpg",
  },
  {
    id: "bra6",
    name: "Strapless Bra",
    collection: "bras",
    category: "strapless",
    price: "Rs. 1,450",
    description: "Stay-up strapless bra perfect for off-shoulder outfits.",
    image: "/straplessbra.jpg",
  },
  {
    id: "bra7",
    name: "Convertible Bra",
    collection: "bras",
    category: "minimizer",
    price: "Rs. 1,550",
    description: "Multi-way bra for versatile styling.",
    image: "/plungebra.jpg",
  },
  {
    id: "bra8",
    name: "Plunge Bra",
    collection: "bras",
    category: "push-up",
    price: "Rs. 1,700",
    description: "Deep neckline plunge bra for bold looks.",
    image: "/plungebra3.jpg",
  },
  {
    id: "bra9",
    name: "Front Closure Bra",
    collection: "bras",
    category: "full-coverage",
    price: "Rs. 1,380",
    description: "Easy to wear front-closure design.",
    image: "/frontclosure.jpg",
  },
  {
    id: "bra10",
    name: "Full Coverage Bra",
    collection: "bras",
    category: "full-coverage",
    price: "Rs. 1,600",
    description: "Maximum coverage with style.",
    image: "/paddedbra3.jpg",
  },

  // === Panties ===
  {
    id: "panty1",
    name: "Lace Panty",
    collection: "panties",
    category: "lace",
    price: "Rs. 850",
    description: "Elegant lace panty with full back coverage and soft lining.",
    image: "/lacepanty.jpg",
  },
  {
    id: "panty2",
    name: "High-Waist Panty",
    collection: "panties",
    category: "high-waist",
    price: "Rs. 780",
    description: "Comfortable high-waist panty designed for everyday wear.",
    image: "/panty2.jpg",
  },
  {
    id: "panty3",
    name: "Seamless Panty",
    collection: "panties",
    category: "seamless",
    price: "Rs. 720",
    description: "Invisible seamless panty for tight outfits and soft feel.",
    image: "/seamless.jpg",
  },
  {
    id: "panty4",
    name: "Cotton Bikini Panty",
    collection: "panties",
    category: "bikini",
    price: "Rs. 700",
    description: "Breathable cotton panty for comfort.",
    image: "/cotton.jpg",
  },
  {
    id: "panty5",
    name: "Printed Briefs",
    collection: "panties",
    category: "cotton",
    price: "Rs. 850",
    description: "Stylish printed briefs in soft material.",
    image: "/lace1.jpg",
  },
  {
    id: "panty6",
    name: "Thong Panty",
    collection: "panties",
    category: "thong",
    price: "Rs. 880",
    description: "Minimal coverage thong for a seamless feel.",
    image: "/thong.jpg",
  },
  {
    id: "panty7",
    name: "Boyshorts",
    collection: "panties",
    category: "boyshort",
    price: "Rs. 800",
    description: "Boyshort style panty for comfort and coverage.",
    image: "/random.jpg",
  },
  {
    id: "panty8",
    name: "Mesh Panty",
    collection: "panties",
    category: "hipster",
    price: "Rs. 950",
    description: "Breathable mesh panty with lace trim.",
    image: "/meshpanty.jpg",
  },
  {
    id: "panty9",
    name: "No-Show Panty",
    collection: "panties",
    category: "seamless",
    price: "Rs. 730",
    description: "Designed to vanish under clothes.",
    image: "/vanishpanty.jpg",
  },
  {
    id: "panty10",
    name: "Luxury Satin Panty",
    collection: "panties",
    category: "lace",
    price: "Rs. 990",
    description: "Smooth satin panty for luxury comfort.",
    image: "/satin.jpg",
  },

   // === Lingerie ===
  {
    id: "lingerie1",
    name: "Lace Babydoll Set",
    collection: "lingerie",
    category: "lace-set",
    price: "Rs. 2,200",
    description: "Sensual babydoll with sheer lace and matching thong.",
    image: "/babydoll.jpg",
  },
  {
    id: "lingerie2",
    name: "Silk Bodysuit",
    collection: "lingerie",
    category: "bodysuit",
    price: "Rs. 2,500",
    description: "Smooth silk bodysuit with deep neckline and adjustable straps.",
    image: "/bodysuit.jpg",
  },
  {
    id: "lingerie3",
    name: "Teddy Lace Set",
    collection: "lingerie",
    category: "teddy",
    price: "Rs. 2,100",
    description: "Fitted teddy with floral lace and ribbon details.",
    image: "/teadyset.jpg",
  },
  {
    id: "lingerie4",
    name: "Mesh Bodysuit",
    collection: "lingerie",
    category: "bodysuit",
    price: "Rs. 2,300",
    description: "Mesh design bodysuit for a sultry look.",
    image: "/meshbodysuit.jpg",
  },
  {
    id: "lingerie5",
    name: "Lace Chemise",
    collection: "lingerie",
    category: "chemise",
    price: "Rs. 2,000",
    description: "Short lace chemise with adjustable straps.",
    image: "/lace.jpg",
  },
  {
    id: "lingerie6",
    name: "Caged Bodysuit",
    collection: "lingerie",
    category: "bodysuit",
    price: "Rs. 2,400",
    description: "Edgy caged bodysuit with stretch material.",
    image: "/caged.jpg",
  },
  {
    id: "lingerie7",
    name: "Velvet Teddy",
    collection: "lingerie",
    category: "teddy",
    price: "Rs. 2,350",
    description: "Rich velvet teddy with a deep V cut.",
    image: "/velvet.jpg",
  },
  {
    id: "lingerie8",
    name: "Embroidered Bodysuit",
    collection: "lingerie",
    category: "bodysuit",
    price: "Rs. 2,550",
    description: "Delicate embroidery work on sheer mesh.",
    image: "/embroidered.jpg",
  },
  {
    id: "lingerie9",
    name: "Satin Slip Dress",
    collection: "lingerie",
    category: "coreset",
    price: "Rs. 2,450",
    description: "Soft satin slip dress for a luxurious night.",
    image: "/satin.jpg",
  },
  {
    id: "lingerie10",
    name: "Open-Back Teddy",
    collection: "lingerie",
    category: "teddy",
    price: "Rs. 2,600",
    description: "Daring open-back lace teddy.",
    image: "/backless.jpg",
  },

 
  // === Shapewear ===
  {
    id: "shapewear1",
    name: "High-Waist Tummy Tuck",
    collection: "shapewear",
    category: "tummy-tucker",
    price: "Rs. 2,100",
    description: "Firm control shapewear with high-waist and breathable fabric.",
    image: "/tummy.jpg",
  },
  {
    id: "shapewear2",
    name: "Mid-Thigh Shaper",
    collection: "shapewear",
    category: "thigh-shaper",
    price: "Rs. 2,000",
    description: "Smooth shaping from waist to thighs for a flawless silhouette.",
    image: "/thigh.jpg",
  },
  {
    id: "shapewear3",
    name: "Waist Trainer Corset",
    collection: "shapewear",
    category: "waist-shaper",
    price: "Rs. 2,600",
    description: "Steel-boned waist trainer for hourglass shaping.",
    image: "/categoryshapewear.jpg",
  },
  {
    id: "shapewear4",
    name: "Seamless Body Briefer",
    collection: "shapewear",
    category: "control-briefs",
    price: "Rs. 2,200",
    description: "All-in-one body shaper with seamless construction.",
    image: "/fullbody.jpg",
  },
  {
    id: "shapewear5",
    name: "Pragnant ladies recovery belt",
    collection: "shapewear",
    category: "waist-shaper",
    price: "Rs. 2,300",
    description: "Supportive band for c-section recovery and waist shaping.",
    image: "/moms.jpg",
  },
  {
    id: "shapewear6",
    name: "Butt Lifter Shorts",
    collection: "shapewear",
    category: "full-body",
    price: "Rs. 1,900",
    description: "Enhance your curves with built-in lift and shape.",
    image: "/butt.jpg",
  },
  {
    id: "shapewear7",
    name: "Full Body Suit",
    collection: "shapewear",
    category: "full-body",
    price: "Rs. 2,750",
    description: "Full body coverage for total contouring.",
    image: "/fullbody.jpg",
  },
  {
    id: "shapewear8",
    name: "Open-Bust Slip",
    collection: "shapewear",
    category: "control-briefs",
    price: "Rs. 2,350",
    description: "Control slip for under dresses with open bust design.",
    image: "/openbust.jpg",
  },
  {
    id: "shapewear9",
    name: "Arm Slimmers",
    collection: "shapewear",
    category: "control-briefs",
    price: "Rs. 1,500",
    description: "Light compression arm sleeves for toning.",
    image: "/armslimmer.jpg",
  },
  {
    id: "shapewear10",
    name: "Hip Enhancer Pads",
    collection: "shapewear",
    category: "thigh-shaper",
    price: "Rs. 1,800",
    description: "Padded shapewear for natural hip curves.",
    image: "/hipenhancer.jpg",
  },

  // === Bridal Wear ===
  {
    id: "bridal1",
    name: "Embroidered Bridal Corset",
    collection: "bridal",
    category: "white-corset",
    price: "Rs. 3,200",
    description: "Elegant corset with bridal embroidery.",
    image: "/coreset.jpg",
  },
  {
    id: "bridal2",
    name: "Bridal Lingerie Set",
    collection: "bridal",
    category: "lace-bridal-set",
    price: "Rs. 3,400",
    description: "Romantic  lace lingerie set for brides.",
    image: "/bridallingerie.jpg",
  },
  {
    id: "bridal3",
    name: "Silk Robe with Lace",
    collection: "bridal",
    category: "honeymoon-slip",
    price: "Rs. 2,800",
    description: "Luxurious silk robe with lace trim.",
    image: "/silkrope.jpg",
  },
  {
    id: "bridal4",
    name: "Backless Bridal Slip",
    collection: "bridal",
    category: "bridal-nightgown",
    price: "Rs. 2,900",
    description: "Smooth backless slip ideal for wedding dresses.",
    image: "/slip.jpg",
  },
  {
    id: "bridal5",
    name: "Sheer Bridal Chemise",
    collection: "bridal",
    category: "lace-bridal-set",
    price: "Rs. 3,100",
    description: "Sheer chemise with intricate detailing.",
    image: "/chemise1.jpg",
  },
  {
    id: "bridal6",
    name: "Strapless Bridal Bodysuit",
    collection: "bridal",
    category: "bridal-nightgown",
    price: "Rs. 3,500",
    description: "Supportive strapless bodysuit for under gowns.",
    image: "/undergown.jpg",
  },
  {
    id: "bridal7",
    name: "White Bridal Garter Set",
    collection: "bridal",
    category: "bridal-rope",
    price: "Rs. 1,600",
    description: "Classic white garter set for wedding night.",
    image: "/garter.jpg",
  },
  {
    id: "bridal8",
    name: "Lace Bustier Bridal Set",
    collection: "bridal",
    category: "lace-bridal-set",
    price: "Rs. 3,300",
    description: "Structured bustier with delicate lace overlay.",
    image: "/strapless.jpg",
  },
  {
    id: "bridal9",
    name: "Bridal Bralette and Panty",
    collection: "bridal",
    category: "white-corset",
    price: "Rs. 2,200",
    description: "Soft bralette paired with matching panty.",
    image: "/braty.jpg",
  },
  {
    id: "bridal10",
    name: "Embellished Bridal Gown Slip",
    collection: "bridal",
    category: "honeymoon-slip",
    price: "Rs. 3,600",
    description: "Beautifully embellished slip under bridal gowns.",
    image: "/slip.jpg",
  },

  // === BDSM Wear ===
  {
    id: "bdsm1",
    name: "handcuffs",
    collection: "bdsm",
    category: "cuffs",
    price: "Rs. 4,200",
    description: "Tight your girl hand with these romantic handcuffs.",
    image: "/trending1.png",
  },
  {
    id: "bdsm2",
    name: "BDSM body suit",
    collection: "bdsm",
    category: "dresskit",
    price: "Rs. 3,800",
    description: "This full sexy Bdsm body suit when you wear it you can't control your partner",
    image: "/trending7.png",
  },
  {
    id: "bdsm3",
    name: "Whip",
    collection: "bdsm",
    category: "whip",
    price: "Rs. 2,900",
    description: "OMG you can't forget these product in bdsm this is amazing highly recomended without this bdsm is incomplete .",
    image: "/trending6.png",
  },
  {
    id: "bdsm4",
    name: "Neck Collar",
    collection: "bdsm",
    category: "collar",
    price: "Rs. 3,200",
    description: "This neck collar is amazing .",
    image: "/trending4.png",
  },
  {
    id: "bdsm5",
    name: "Bodystocking",
    collection: "bdsm",
    category: "pantyhose",
    price: "Rs. 2,750",
    description: "Alluring full-body fishnet stocking.",
    image: "/trending10.jpg",
  },
  {
    id: "bdsm6",
    name: "Gagball",
    collection: "bdsm",
    category: "gagball",
    price: "Rs. 4,600",
    description: "Eplore this premium product.",
    image: "/trending6.png",
  },
  {
    id: "bdsm7",
    name: "Bondage Rope",
    collection: "bdsm",
    category: "rope",
    price: "Rs. 3,900",
    description: "Tie your partner with this bondage rope.",
    image: "/trending5.png",
  },
  {
    id: "bdsm8",
    name: "AnkleCuffs",
    collection: "bdsm",
    category: "cuffs",
    price: "Rs. 3,100",
    description: "These are amazing to tie in bdsm.",
    image: "/trending2.png",
  },
  {
    id: "bdsm9",
    name: "Eyepatch",
    collection: "bdsm",
    category: "eyepatch",
    price: "Rs. 3,300",
    description: "Best premium eyepatches.",
    image: "/trending6.png",
  },
  {
    id: "bdsm10",
    name: "ThighCuffs",
    collection: "bdsm",
    category: "cuffs",
    price: "Rs. 3,500",
    description: "These thigh cuffs looks sexy and adorable.",
    image: "/trending4.png",
  }
];



